# Generated by Django 6.0.4 on 2026-05-25 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 5, 25, 9, 36, 38, 947110, tzinfo=datetime.timezone.utc)),
        ),
    ]
