# Generated by Django 6.0.4 on 2026-05-25 11:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 25, 11, 50, 26, 847512, tzinfo=datetime.timezone.utc)),
        ),
    ]
