# Generated by Django 6.0.4 on 2026-05-26 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 26, 4, 27, 46, 981033, tzinfo=datetime.timezone.utc)),
        ),
    ]
