# Generated by Django 6.0.4 on 2026-06-06 04:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_task_created_at_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 6, 4, 19, 35, 802628, tzinfo=datetime.timezone.utc)),
        ),
    ]
