# Generated by Django 6.0.4 on 2026-06-06 04:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 6, 4, 27, 36, 359487, tzinfo=datetime.timezone.utc)),
        ),
    ]
