# Generated by Django 6.0.4 on 2026-06-08 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 8, 7, 21, 42, 112477, tzinfo=datetime.timezone.utc)),
        ),
    ]
