# Generated by Django 6.0.4 on 2026-06-09 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 9, 5, 49, 0, 78210, tzinfo=datetime.timezone.utc)),
        ),
    ]
