# Generated by Django 6.0.4 on 2026-06-10 03:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 10, 3, 49, 2, 66037, tzinfo=datetime.timezone.utc)),
        ),
    ]
