# Generated by Django 6.0.4 on 2026-06-11 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_category_alter_task_due_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 11, 15, 41, 26, 821448, tzinfo=datetime.timezone.utc)),
        ),
    ]
