# Generated by Django 6.0.4 on 2026-06-11 15:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_rename_title_category_name_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 11, 15, 43, 43, 880126, tzinfo=datetime.timezone.utc)),
        ),
    ]
