# Generated by Django 6.0.4 on 2026-06-12 02:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_category_options_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 2, 33, 54, 877708, tzinfo=datetime.timezone.utc)),
        ),
    ]
