# Generated by Django 6.0.4 on 2026-06-12 05:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 5, 33, 48, 351830, tzinfo=datetime.timezone.utc)),
        ),
    ]
