# Generated by Django 6.0.4 on 2026-06-12 06:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_task_category_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 12, 6, 27, 24, 65864, tzinfo=datetime.timezone.utc)),
        ),
    ]
