# Generated by Django 6.0.4 on 2026-06-13 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 13, 2, 42, 36, 193296, tzinfo=datetime.timezone.utc)),
        ),
    ]
