# Generated by Django 6.0.4 on 2026-06-13 06:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0023_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 13, 6, 26, 5, 571974, tzinfo=datetime.timezone.utc)),
        ),
    ]
