# Generated by Django 6.0.4 on 2026-06-13 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(default=datetime.datetime(2026, 6, 13, 12, 14, 20, 487725, tzinfo=datetime.timezone.utc)),
        ),
    ]
